name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # paths must match your repo (underscores)
        service: [ backend/order_service, backend/product_service, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python services (backends) ----------
      - name: Set up Python
        if: ${{ hashFiles(format('{0}/requirements.txt', matrix.service)) != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        if: ${{ hashFiles(format('{0}/requirements.txt', matrix.service)) != '' }}
        run: |
          cd ${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ---------- Node service (frontend) ----------
      - name: Set up Node.js
        if: ${{ hashFiles(format('{0}/package.json', matrix.service)) != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node deps
        if: ${{ hashFiles(format('{0}/package.json', matrix.service)) != '' }}
        run: |
          cd ${{ matrix.service }}
          npm ci || npm install

      # ---------- Build Docker for all services ----------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          push: false
          tags: temp/${{ matrix.service }}:ci
