name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ backend/product_service, backend/order_service, frontend ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd ${{ matrix.service }} && npm install
      - name: Run tests
        run: cd ${{ matrix.service }} && npm test
