name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-services:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ backend/order_service, backend/product_service, frontend ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (if requirements.txt exists)
        if: hashFiles('${{ matrix.service }}/requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        if: hashFiles('${{ matrix.service }}/requirements.txt') != ''
        run: |
          cd ${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          push: false
          tags: temp/${{ matrix.service }}:ci
